remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: [KPF BERT]
description: [KPF BERT 소개자료]
url: "https://kpfbert.github.io/kpfbert/"
markdown: kramdown

google_analytics: [G-0TXTER2CXK]
